#!/bin/sh                                          

case "$1" in
    start)
	printf "Starting axp209: "
	start-stop-daemon -S -q -p /var/run/axp209.pid --exec /usr/bin/enable-no-limit
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Stopping axp209: "
	start-stop-daemon -K -q -p /var/run/axp209.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

